// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmVtbB6D_He9eAw97ExNYZsALcf5QY1dk',
    appId: '1:288156635886:web:18bb49a8eee994971059ff',
    messagingSenderId: '288156635886',
    projectId: 'anket-e3aed',
    authDomain: 'anket-e3aed.firebaseapp.com',
    storageBucket: 'anket-e3aed.firebasestorage.app',
    measurementId: 'G-XK8Q24GGQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcnfFYcRJJja83-FC0k8CHpH6OUB4w6iA',
    appId: '1:288156635886:android:5dcda604128a43901059ff',
    messagingSenderId: '288156635886',
    projectId: 'anket-e3aed',
    storageBucket: 'anket-e3aed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo6YtNaF-AHVAYUa5tdFUIe6TpYz0mL0U',
    appId: '1:288156635886:ios:f5e35cdad6ab47741059ff',
    messagingSenderId: '288156635886',
    projectId: 'anket-e3aed',
    storageBucket: 'anket-e3aed.firebasestorage.app',
    iosBundleId: 'com.example.anket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmVtbB6D_He9eAw97ExNYZsALcf5QY1dk',
    appId: '1:288156635886:web:9396623b9ba7e1461059ff',
    messagingSenderId: '288156635886',
    projectId: 'anket-e3aed',
    authDomain: 'anket-e3aed.firebaseapp.com',
    storageBucket: 'anket-e3aed.firebasestorage.app',
    measurementId: 'G-95F6FT27BN',
  );
}
